### ISSUE TITLE
dashboard 페이지 컴포넌트 분리

### ISSUE THREAD

**Issue by msdio** [team-vera6/career-client#33]
modal open에 관련된 useState가 여기에 작성되면 컴포넌트 전체가 client 사이드에서 렌더링 되어야 해서요 ㅜ
추후 로직 수정할 때 TextEditor 관련 컴포넌트와 훅 분리해서 modalList 기본 구조가 SSR로 처리될  있게 수정하면 좋을 것 같습니다 !! 🙂

_Originally posted by @MeaninGood in https://github.com/team-vera6/career-client/pull/30#discussion_r1683841889_

**Comment by MeaninGood** [comment]
👍
